export default function () {
  return {
    'ai-content-form-generation': {
      name: 'AI Content & Form Data',
      description:
        'Generate content or structured form data with OpenRouter, ChatGPT, or Gemini',
      icon: 'riRobot2Line',
      component: 'BlockBasic',
      editComponent: 'EditAiContentFormGeneration',
      category: 'general',
      inputs: 1,
      outputs: 1,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['prompt', 'systemPrompt', 'schemaJson'],
      data: {
        disableBlock: false,
        description: '',
        experimentalEnabled: false,
        stopOnError: false,
        provider: 'openrouter',
        model: 'openai/gpt-4o-mini',
        temperature: 0.2,
        maxTokens: 900,
        timeoutMs: 45000,
        retries: 1,
        systemPrompt: '',
        prompt: '',
        usePageContext: false,
        useFormContext: false,
        maxPageTextLength: 6000,
        schemaMode: false,
        strictSchema: false,
        schemaJson: '',
        assignVariable: false,
        variableName: '',
        saveData: false,
        dataColumn: '',
      },
    },
    'autonomous-ai': {
      name: 'Autonomous AI',
      description:
        'Analyze page state, decide the next action, and execute bounded browser automation',
      icon: 'riCompass3Line',
      component: 'BlockBasic',
      editComponent: 'EditAutonomousAi',
      category: 'general',
      inputs: 1,
      outputs: 1,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['goal', 'systemPrompt'],
      data: {
        disableBlock: false,
        description: '',
        experimentalEnabled: false,
        stopOnError: false,
        provider: 'openrouter',
        model: 'openai/gpt-4o-mini',
        temperature: 0.1,
        maxTokens: 900,
        timeoutMs: 45000,
        retries: 1,
        maxSteps: 8,
        maxFailures: 3,
        maxHistoryChars: 24000,
        systemPrompt: '',
        goal: '',
        usePageContext: true,
        maxPageTextLength: 5000,
        assignVariable: false,
        variableName: '',
        saveData: false,
        dataColumn: '',
      },
    },
  };
}
